'use strict';

// 节日配置单一数据源：服务端用于构建提示词，前端通过 /api/festivals 获取展示信息。
// 每个节日绑定专属风格（styleName/persona/tone）与插画场景（scene/palette），
// 以及整套主题配色（theme），实现“选节日即绑定风格与视觉”。

const FESTIVALS = [
  {
    id: 'teachers-day',
    name: '教师节',
    group: 'cn',
    date: '9月10日',
    match: { type: 'solar', month: 9, day: 10 },
    keyChar: '师',
    en: "Teacher's Day",
    styleName: '感恩敬师',
    persona: '你是一位擅长为教师节创作专属祝福的中文文案作家。',
    tone: '感恩、真挚、温暖，向老师表达敬意与谢意',
    focus: '点出老师在讲台与粉笔间的付出，以及对学生成长的影响',
    taboo: '避免夸张空泛的溢美之词',
    scene: 'a green chalkboard, floating books and pencils, a vase of carnations, warm classroom sunlight',
    palette: 'warm red and gold tones, cozy sincere mood',
    withPerson: true,
    personDetail: 'standing beside the chalkboard, holding a book and a bunch of flowers',
    theme: { primary: '#d9482b', deep: '#b23018', soft: '#fbe3da', amber: '#e79a1f', gold: '#c8912a', bg1: '#fff5e6', bg2: '#ffe9d9', bg3: '#ffe0dc', ink: '#3b2416', line: '#eddcc9' }
  },
  {
    id: 'spring-festival',
    name: '春节',
    group: 'cn',
    date: '正月初一',
    match: { type: 'lunar', month: 1, day: 1 },
    keyChar: '春',
    en: 'Chinese New Year',
    styleName: '喜庆热烈',
    persona: '你是一位擅长撰写春节祝福的中文文案作家。',
    tone: '喜庆、热烈、吉祥如意，洋溢对新一年的美好期许',
    focus: '融入新春团圆、辞旧迎新、福气临门的意象',
    taboo: '避免使用晦气或低沉的字眼',
    scene: 'red lanterns, spring festival couplets, plum blossoms, gold ingots, firecrackers, a festive home',
    palette: 'vivid red and gold, jubilant festive mood',
    withPerson: true,
    personDetail: 'wearing a red festive sweater, holding a paper-cut window decoration and a red lantern',
    theme: { primary: '#c81e2b', deep: '#8c0f1a', soft: '#fbe0e0', amber: '#e0a020', gold: '#c8912a', bg1: '#fff4ee', bg2: '#ffe0d8', bg3: '#ffd0c4', ink: '#3a1a12', line: '#f0d6cc' }
  },
  {
    id: 'lantern',
    name: '元宵节',
    group: 'cn',
    date: '正月十五',
    match: { type: 'lunar', month: 1, day: 15 },
    keyChar: '宵',
    en: 'Lantern Festival',
    styleName: '团圆温馨',
    persona: '你是一位擅长撰写元宵节祝福的中文文案作家。',
    tone: '团圆、温馨、灯火可亲，带一丝甜蜜',
    focus: '融入汤圆、花灯、圆月与阖家团圆的意象',
    taboo: '避免冷清或离别的表述',
    scene: 'glowing paper lanterns, a bowl of sweet rice balls, a bright full moon, a lantern riddle stall',
    palette: 'warm orange and soft red, cozy reunion mood',
    withPerson: true,
    personDetail: 'holding a glowing rabbit lantern under the full moon',
    theme: { primary: '#d94f2b', deep: '#9c2f14', soft: '#fde6d8', amber: '#e8a23a', gold: '#c98a2a', bg1: '#fff7ec', bg2: '#ffe8d0', bg3: '#ffdcc0', ink: '#3d2213', line: '#f0dcc4' }
  },
  {
    id: 'dragon-boat',
    name: '端午节',
    group: 'cn',
    date: '五月初五',
    match: { type: 'lunar', month: 5, day: 5 },
    keyChar: '端',
    en: 'Dragon Boat Festival',
    styleName: '安康顺遂',
    persona: '你是一位擅长撰写端午节祝福的中文文案作家。',
    tone: '古朴、安稳、祈愿安康顺遂',
    focus: '融入粽子、龙舟、艾草香囊与祛病纳福的意象',
    taboo: '端午祝福宜用“安康”“顺遂”，避免“快乐”一词',
    scene: 'dragon boats racing on a river, zongzi wrapped in bamboo leaves, mugwort and sachets, rippling water',
    palette: 'deep green and warm gold, traditional peaceful mood',
    withPerson: true,
    personDetail: 'holding a home-made zongzi and a fragrant sachet by the river',
    theme: { primary: '#2f6b4f', deep: '#1d4734', soft: '#dcebe2', amber: '#c8912a', gold: '#a8761f', bg1: '#f0f7f1', bg2: '#e0efe6', bg3: '#cfe6da', ink: '#1f3528', line: '#d3e3d8' }
  },
  {
    id: 'qixi',
    name: '七夕节',
    group: 'cn',
    date: '七月初七',
    match: { type: 'lunar', month: 7, day: 7 },
    keyChar: '夕',
    en: 'Qixi Festival',
    styleName: '浪漫甜蜜',
    persona: '你是一位擅长撰写七夕节祝福的中文文案作家。',
    tone: '浪漫、温柔、甜蜜，带着星河与思念的意境',
    focus: '融入鹊桥、银河、牛郎织女与相守相伴的意象',
    taboo: '避免过于直白或庸俗的表述',
    scene: 'a magpie bridge across the Milky Way, twinkling stars, glowing lanterns, blooming flowers',
    palette: 'soft pink and deep blue, dreamy romantic mood',
    withPerson: true,
    personDetail: 'gazing at the starry sky, holding a small glowing lantern',
    theme: { primary: '#c2456e', deep: '#8c284c', soft: '#fbe0ea', amber: '#d98aa8', gold: '#c16b8a', bg1: '#fff4f8', bg2: '#ffe4ee', bg3: '#ffd6e4', ink: '#3d1a28', line: '#f2d3e0' }
  },
  {
    id: 'mid-autumn',
    name: '中秋节',
    group: 'cn',
    date: '八月十五',
    match: { type: 'lunar', month: 8, day: 15 },
    keyChar: '秋',
    en: 'Mid-Autumn Festival',
    styleName: '团圆思念',
    persona: '你是一位擅长撰写中秋节祝福的中文文案作家。',
    tone: '温婉、隽永、思亲念远，寄情于月',
    focus: '融入满月、月饼、桂花与人间团圆的意象',
    taboo: '避免伤感过重，保持温柔的期盼',
    scene: 'a bright full moon over osmanthus blossoms, stacked mooncakes, glowing lanterns, a quiet courtyard',
    palette: 'deep night blue and warm gold, serene reunion mood',
    withPerson: true,
    personDetail: 'sitting in a courtyard with a cup of tea, looking up at the full moon',
    theme: { primary: '#2b4c8c', deep: '#1a2f61', soft: '#dde6f7', amber: '#e0a020', gold: '#c8912a', bg1: '#f2f5ff', bg2: '#e3eaff', bg3: '#d3ddff', ink: '#182448', line: '#d3ddff' }
  },
  {
    id: 'double-ninth',
    name: '重阳节',
    group: 'cn',
    date: '九月初九',
    match: { type: 'lunar', month: 9, day: 9 },
    keyChar: '阳',
    en: 'Double Ninth Festival',
    styleName: '敬老康健',
    persona: '你是一位擅长撰写重阳节祝福的中文文案作家。',
    tone: '厚重、恭敬、祈愿长寿康健',
    focus: '融入登高、菊花、茱萸与尊老敬老的意象',
    taboo: '避免轻浮玩笑',
    scene: 'chrysanthemums in full bloom, autumn hills for climbing, dogwood sprigs, a clear high sky',
    palette: 'amber and deep brown, dignified autumn mood',
    withPerson: true,
    personDetail: 'climbing a hill with a walking stick, surrounded by chrysanthemums',
    theme: { primary: '#b5651d', deep: '#7d4210', soft: '#f7e6d2', amber: '#e0a020', gold: '#c8912a', bg1: '#fff6e9', bg2: '#ffead0', bg3: '#ffdcb5', ink: '#3d2712', line: '#efdcc4' }
  },
  {
    id: 'national-day',
    name: '国庆节',
    group: 'cn',
    date: '10月1日',
    match: { type: 'solar', month: 10, day: 1 },
    keyChar: '庆',
    en: 'National Day',
    styleName: '家国情怀',
    persona: '你是一位擅长撰写国庆节祝福的中文文案作家。',
    tone: '豪迈、昂扬、饱含家国情怀与自豪',
    focus: '融入锦绣山河、盛世华诞与美好祝愿的意象',
    taboo: '保持积极庄重',
    scene: 'red flags waving, bright fireworks over city skylines, doves flying, golden autumn fields',
    palette: 'rich red and golden, majestic celebratory mood',
    withPerson: true,
    personDetail: 'standing on a rooftop watching fireworks, holding a small flag',
    theme: { primary: '#c81e2b', deep: '#8c0f1a', soft: '#fbe0e0', amber: '#e6b422', gold: '#c8912a', bg1: '#fff3f0', bg2: '#ffe0da', bg3: '#ffd0c6', ink: '#3a1512', line: '#f0d4ce' }
  },
  {
    id: 'qingming',
    name: '清明节',
    group: 'cn',
    date: '4月4日前后',
    match: { type: 'solar-range', month: 4, days: [4, 5, 6] },
    keyChar: '明',
    en: 'Qingming Festival',
    styleName: '追思怀远',
    persona: '你是一位擅长撰写清明节寄语的中文文案作家。',
    tone: '素雅、庄重、追思怀远，寄托思念与祝福',
    focus: '融入春雨、新柳、青团与缅怀先人的意象',
    taboo: '清明为追思之节，严禁使用“快乐”等欢庆字眼，改用“安康”“安好”“思念”',
    scene: 'soft spring rain, fresh willow branches, green rice balls, distant misty mountains, gentle and serene',
    palette: 'fresh green and soft grey, calm respectful mood',
    withPerson: false,
    theme: { primary: '#4f7a5a', deep: '#2f5138', soft: '#e2efe4', amber: '#9bb59a', gold: '#7d9a7d', bg1: '#f3f8f3', bg2: '#e7f0e8', bg3: '#dce9de', ink: '#26382a', line: '#d5e5d9' }
  },
  {
    id: 'new-year',
    name: '元旦',
    group: 'cn',
    date: '1月1日',
    match: { type: 'solar', month: 1, day: 1 },
    keyChar: '旦',
    en: 'New Year',
    styleName: '辞旧迎新',
    persona: '你是一位擅长撰写元旦祝福的中文文案作家。',
    tone: '明快、昂扬、满怀对崭新一年的期待',
    focus: '融入新年伊始、万象更新与美好愿景的意象',
    taboo: '避免怀旧伤感',
    scene: 'fireworks at midnight, a calendar turning to a new year, sparkling stars, fresh snow and sunrise',
    palette: 'bright blue and gold, hopeful fresh mood',
    withPerson: true,
    personDetail: 'raising a cup to the new year under fireworks',
    theme: { primary: '#4b5cc4', deep: '#2f3d92', soft: '#e0e4fb', amber: '#e0a020', gold: '#c8912a', bg1: '#f4f6ff', bg2: '#e6ebff', bg3: '#d8e0ff', ink: '#1c2350', line: '#d6ddff' }
  },
  {
    id: 'christmas',
    name: '圣诞节',
    group: 'world',
    date: '12月25日',
    match: { type: 'solar', month: 12, day: 25 },
    keyChar: '诞',
    en: 'Christmas',
    styleName: '欢乐温馨',
    persona: '你是一位擅长撰写圣诞节祝福的中文文案作家。',
    tone: '欢乐、温馨、缤纷，带着冬日暖意',
    focus: '融入圣诞树、铃铛、雪花与礼物交换的意象',
    taboo: '避免宗教争议性表述',
    scene: 'a decorated Christmas tree, twinkling string lights, snowflakes, wrapped gift boxes, stockings',
    palette: 'classic red and green with warm gold lights, cheerful cozy mood',
    withPerson: true,
    personDetail: 'wearing a knitted sweater and a red scarf, holding a gift box by the Christmas tree',
    theme: { primary: '#b3242e', deep: '#7d131b', soft: '#f7dfe1', amber: '#2f7a4a', gold: '#c8912a', bg1: '#f6fbf7', bg2: '#e7f4ea', bg3: '#d6ecdc', ink: '#23321f', line: '#d5e8da' }
  },
  {
    id: 'thanksgiving',
    name: '感恩节',
    group: 'world',
    date: '11月第四个星期四',
    match: { type: 'nth-weekday', month: 11, weekday: 4, nth: 4 },
    keyChar: '感',
    en: 'Thanksgiving',
    styleName: '感恩温暖',
    persona: '你是一位擅长撰写感恩节祝福的中文文案作家。',
    tone: '真挚、丰盛、温暖，表达由衷的感谢',
    focus: '融入秋收、南瓜、火鸡与家人围坐的意象',
    taboo: '避免空洞应付',
    scene: 'autumn harvest pumpkins, a warm dinner table, golden maple leaves, candles and wheat sheaves',
    palette: 'warm amber and russet, abundant grateful mood',
    withPerson: true,
    personDetail: 'standing by a harvest table holding a pumpkin, wearing a cozy autumn scarf',
    theme: { primary: '#b5651d', deep: '#7d4210', soft: '#f7e6d2', amber: '#d99a2b', gold: '#b07d1f', bg1: '#fff7ea', bg2: '#ffecd2', bg3: '#ffe0b8', ink: '#3d2712', line: '#efdcc0' }
  },
  {
    id: 'halloween',
    name: '万圣节',
    group: 'world',
    date: '10月31日',
    match: { type: 'solar', month: 10, day: 31 },
    keyChar: '圣',
    en: 'Halloween',
    styleName: '搞怪俏皮',
    persona: '你是一位擅长撰写万圣节祝福的中文文案作家。',
    tone: '搞怪、俏皮、有趣，带着可爱的“惊吓”',
    focus: '融入南瓜灯、糖果、蝙蝠与奇趣装扮的意象',
    taboo: '保持轻松可爱，避免恐怖血腥',
    scene: 'glowing jack-o-lanterns, candy buckets, friendly bats and black cats, a whimsical haunted house',
    palette: 'purple and orange, playful spooky-but-cute mood',
    withPerson: true,
    personDetail: 'wearing a cute pumpkin costume and a witch hat, holding a basket of candy',
    theme: { primary: '#7a3fa0', deep: '#4f2370', soft: '#ede0f7', amber: '#e07b1f', gold: '#c8912a', bg1: '#faf5ff', bg2: '#f0e6ff', bg3: '#e6d6ff', ink: '#2c1a3d', line: '#e2d3f2' }
  },
  {
    id: 'valentines',
    name: '情人节',
    group: 'world',
    date: '2月14日',
    match: { type: 'solar', month: 2, day: 14 },
    keyChar: '情',
    en: "Valentine's Day",
    styleName: '浪漫浓情',
    persona: '你是一位擅长撰写情人节祝福的中文文案作家。',
    tone: '浪漫、浓情、甜蜜，充满心动与陪伴',
    focus: '融入玫瑰、巧克力、心形与相守相伴的意象',
    taboo: '避免过于直白露骨',
    scene: 'a bouquet of red roses, heart-shaped chocolates, floating balloons, warm candlelight',
    palette: 'rose red and blush pink, romantic sweet mood',
    withPerson: true,
    personDetail: 'holding a bouquet of roses, smiling warmly under soft bokeh lights',
    theme: { primary: '#d6336c', deep: '#9c1f4a', soft: '#fbdce8', amber: '#e07b9c', gold: '#c16b8a', bg1: '#fff4f7', bg2: '#ffe1ec', bg3: '#ffd2e2', ink: '#3d1424', line: '#f2d0de' }
  },
  {
    id: 'easter',
    name: '复活节',
    group: 'world',
    date: '春分后第一个星期日',
    match: { type: 'easter' },
    keyChar: '活',
    en: 'Easter',
    styleName: '生机希望',
    persona: '你是一位擅长撰写复活节祝福的中文文案作家。',
    tone: '清新、明快、充满生机与希望',
    focus: '融入彩蛋、兔子、春花与新生的意象',
    taboo: '避免宗教争议性表述',
    scene: 'colorful painted eggs, a fluffy bunny, blooming spring flowers, fresh green meadow',
    palette: 'fresh mint, yellow and pastel pink, bright hopeful mood',
    withPerson: true,
    personDetail: 'holding a painted egg and a small basket, wearing pastel spring clothes',
    theme: { primary: '#3f8f6b', deep: '#266147', soft: '#ddf0e7', amber: '#e6b422', gold: '#c8912a', bg1: '#f4fbf6', bg2: '#e4f5ea', bg3: '#d3eedd', ink: '#1c3a2a', line: '#d2e9db' }
  },
  {
    id: 'mothers-day',
    name: '母亲节',
    group: 'world',
    date: '5月第二个星期日',
    match: { type: 'nth-weekday', month: 5, weekday: 0, nth: 2 },
    keyChar: '母',
    en: "Mother's Day",
    styleName: '感恩母爱',
    persona: '你是一位擅长撰写母亲节祝福的中文文案作家。',
    tone: '温柔、深情、感恩，倾诉对母亲的爱',
    focus: '融入康乃馨、陪伴与母爱的细碎温暖',
    taboo: '避免敷衍与套话',
    scene: 'pink carnations, a handwritten letter, a cup of warm tea, soft homey light',
    palette: 'soft pink and cream, tender loving mood',
    withPerson: true,
    personDetail: 'holding carnations and a handwritten card, smiling gently',
    theme: { primary: '#d1477a', deep: '#9c2856', soft: '#fbdeea', amber: '#e6a0b8', gold: '#c16b8a', bg1: '#fff4f8', bg2: '#ffe2ee', bg3: '#ffd4e6', ink: '#3d1a2a', line: '#f2d1e0' }
  },
  {
    id: 'fathers-day',
    name: '父亲节',
    group: 'world',
    date: '6月第三个星期日',
    match: { type: 'nth-weekday', month: 6, weekday: 0, nth: 3 },
    keyChar: '父',
    en: "Father's Day",
    styleName: '感恩父爱',
    persona: '你是一位擅长撰写父亲节祝福的中文文案作家。',
    tone: '沉稳、深沉、感恩，表达对父亲的理解与敬爱',
    focus: '融入父爱的沉默、担当与陪伴成长',
    taboo: '避免矫情与过度煽情',
    scene: 'a classic wristwatch, a leather gift box, a mug of coffee, a cozy study with warm light',
    palette: 'deep navy and warm brown, steady heartfelt mood',
    withPerson: true,
    personDetail: 'holding a gift box and a mug, smiling warmly in a study',
    theme: { primary: '#2f5d8c', deep: '#1d3d61', soft: '#dde8f5', amber: '#c8912a', gold: '#a8761f', bg1: '#f2f7fc', bg2: '#e3eef8', bg3: '#d3e0f0', ink: '#172a42', line: '#d5e2f0' }
  },
  {
    id: 'water-splashing',
    name: '泼水节',
    group: 'minority',
    ethnic: '傣族',
    date: '4月13-15日',
    match: { type: 'solar-range', month: 4, days: [13, 14, 15] },
    keyChar: '水',
    en: 'Water Splashing Festival (Dai)',
    styleName: '清凉欢悦',
    persona: '你是一位擅长撰写傣族泼水节祝福的中文文案作家。',
    tone: '清凉、欢悦、真挚，带着水花飞溅的明快',
    focus: '融入泼水祝福、鲜花花环、孔雀羽与新年如水的意象',
    taboo: '避免刻板猎奇，保持对傣族文化的尊重',
    scene: 'crystal water splashing in celebration, colorful flower garlands, peacock feathers, bright blue sky',
    palette: 'fresh aqua blue and warm floral tones, refreshing joyful mood',
    withPerson: true,
    personDetail: 'wearing a graceful traditional Dai dress, splashing water with a flower garland, laughing brightly',
    theme: { primary: '#1f8fa8', deep: '#135f74', soft: '#d9f0f5', amber: '#e6b422', gold: '#c8912a', bg1: '#f0fbfd', bg2: '#ddf4f8', bg3: '#c8ecf3', ink: '#123a46', line: '#cfe9ef' }
  },
  {
    id: 'torch-festival',
    name: '火把节',
    group: 'minority',
    ethnic: '彝族等',
    date: '农历六月二十四',
    match: { type: 'lunar', month: 6, day: 24 },
    keyChar: '火',
    en: 'Torch Festival (Yi)',
    styleName: '火红热烈',
    persona: '你是一位擅长撰写彝族火把节祝福的中文文案作家。',
    tone: '热烈、豪迈、红火，带着篝火夜的豪情',
    focus: '融入火把、篝火、驱虫祈福与五谷丰登的意象',
    taboo: '火把节宜用“红火”“顺遂”“安康”，避免“快乐”一词',
    scene: 'a blazing torch at night, a big campfire with sparks rising, people dancing around the fire, starry sky',
    palette: 'fiery orange and deep red against night blue, warm passionate mood',
    withPerson: true,
    personDetail: 'holding a tall torch with a bright flame under the starry sky',
    theme: { primary: '#d94816', deep: '#9c2c0a', soft: '#fbe0d2', amber: '#e6892a', gold: '#c8912a', bg1: '#fff5ec', bg2: '#ffe6d2', bg3: '#ffd4b5', ink: '#3d1c0a', line: '#f2d5c0' }
  },
  {
    id: 'san-yue-san',
    name: '三月三',
    group: 'minority',
    ethnic: '壮族等',
    date: '农历三月初三',
    match: { type: 'lunar', month: 3, day: 3 },
    keyChar: '歌',
    en: 'Third Month Third Festival (Zhuang)',
    styleName: '对歌传情',
    persona: '你是一位擅长撰写壮族三月三祝福的中文文案作家。',
    tone: '明快、俏皮、含情，带着山歌对唱的清甜',
    focus: '融入五色糯米饭、抛绣球、山歌对唱与春茶的意象',
    taboo: '避免过度娱乐化，保持对歌文化的敬意',
    scene: 'five-color sticky rice in bamboo baskets, a colorful silk ball, bamboo cups of spring tea, blooming peach blossoms',
    palette: 'five festive colors of glutinous rice, bright folk mood',
    withPerson: true,
    personDetail: 'holding a plate of five-color sticky rice and a colorful silk ball, smiling sweetly',
    theme: { primary: '#3f8f4f', deep: '#26613a', soft: '#def0e2', amber: '#e6b422', gold: '#c8912a', bg1: '#f3fbf4', bg2: '#e2f5e6', bg3: '#cdebd4', ink: '#1c3a22', line: '#cfe8d4' }
  },
  {
    id: 'naadam',
    name: '那达慕',
    group: 'minority',
    ethnic: '蒙古族',
    date: '7月中下旬',
    match: { type: 'solar-range', month: 7, days: [18, 19, 20] },
    keyChar: '那',
    en: 'Naadam Festival (Mongolian)',
    styleName: '草原豪情',
    persona: '你是一位擅长撰写蒙古族那达慕祝福的中文文案作家。',
    tone: '豪迈、爽朗、热情，带着草原的风',
    focus: '融入赛马、摔跤、射箭、蒙古包与蓝天白云的意象',
    taboo: '避免刻板印象，保持对草原文化的尊重',
    scene: 'a galloping horse on green grassland, an archer with a bow, a white ger (yurt), blue sky with fluffy clouds',
    palette: 'sky blue and grassland green with festive red, open joyful mood',
    withPerson: true,
    personDetail: 'wearing a traditional deel, riding a horse on the grassland with a confident smile',
    theme: { primary: '#2f6bb5', deep: '#1d4380', soft: '#dde9f8', amber: '#e0a020', gold: '#c8912a', bg1: '#f2f7fe', bg2: '#e0ebfa', bg3: '#cfdff5', ink: '#152c50', line: '#d0e0f2' }
  },
  {
    id: 'shoton',
    name: '雪顿节',
    group: 'minority',
    ethnic: '藏族',
    date: '藏历七月初一前后',
    match: { type: 'solar-range', month: 7, days: [5, 10, 15] },
    keyChar: '雪',
    en: 'Shoton Festival (Tibetan)',
    styleName: '圣洁祥和',
    persona: '你是一位擅长撰写藏族雪顿节祝福的中文文案作家。',
    tone: '圣洁、祥和、温润，带着高原的澄澈',
    focus: '融入晒佛、藏戏、酥油茶与经幡的意象',
    taboo: '宗教氛围庄重，避免轻佻娱乐化',
    scene: 'a golden Thangka Buddha painting on display, colorful prayer flags fluttering, snow mountains in the distance, a bowl of butter tea',
    palette: 'prayer flag colors - blue, white, red, green, gold, sacred serene mood',
    withPerson: true,
    personDetail: 'wearing a traditional Tibetan robe, holding a cup of butter tea, standing before prayer flags',
    theme: { primary: '#8c3fa8', deep: '#5f2370', soft: '#efe2f7', amber: '#e0a020', gold: '#c8912a', bg1: '#f9f4fd', bg2: '#f0e5f8', bg3: '#e2d0f0', ink: '#33184a', line: '#e0d0ec' }
  },
  {
    id: 'eid-fitr',
    name: '开斋节',
    group: 'minority',
    ethnic: '回族、维吾尔族等',
    date: '伊斯兰历十月初一',
    match: { type: 'islamic', month: 10, day: 1 },
    keyChar: '斋',
    en: 'Eid al-Fitr',
    styleName: '祥和团聚',
    persona: '你是一位擅长撰写开斋节祝福的中文文案作家。',
    tone: '祥和、温暖、真挚，带着节日的洁净与欢喜',
    focus: '融入新月、走亲聚会、传统美食与团聚的意象',
    taboo: '宗教节日，表述庄重尊重，避免娱乐化',
    scene: 'a thin crescent moon and stars, a festive table with traditional sweets and dumplings, warm lanterns, a clear night sky',
    palette: 'deep teal and soft gold, serene festive mood',
    withPerson: true,
    personDetail: 'wearing neat festive traditional clothes, holding a plate of sweets, smiling gently',
    theme: { primary: '#1f6b6b', deep: '#124646', soft: '#d8efef', amber: '#c8912a', gold: '#c8912a', bg1: '#f0f9f9', bg2: '#ddf0f0', bg3: '#c8e6e6', ink: '#0f3333', line: '#cde6e6' }
  },
  {
    id: 'eid-al-adha',
    name: '古尔邦节',
    group: 'minority',
    ethnic: '回族、维吾尔族等',
    date: '伊斯兰历十二月十日',
    match: { type: 'islamic', month: 12, day: 10 },
    keyChar: '邦',
    en: 'Eid al-Adha',
    styleName: '庄重祈愿',
    persona: '你是一位擅长撰写古尔邦节祝福的中文文案作家。',
    tone: '庄重、祥和、感恩，带着虔诚与分享的温情',
    focus: '融入祈愿、分享食物与走亲团聚的意象',
    taboo: '宗教节日，表述庄重尊重，避免娱乐化',
    scene: 'a crescent moon over a warm lantern, a table of traditional dumplings and tea, a calm golden evening sky',
    palette: 'warm gold and deep blue, solemn festive mood',
    withPerson: true,
    personDetail: 'wearing clean festive traditional clothes, pouring a cup of tea for a guest, smiling warmly',
    theme: { primary: '#3f5f8c', deep: '#273f61', soft: '#dce6f5', amber: '#c8912a', gold: '#c8912a', bg1: '#f2f6fc', bg2: '#e2eaf7', bg3: '#d0ddf0', ink: '#1a2c4a', line: '#d5e0f0' }
  }
];

const FESTIVAL_MAP = FESTIVALS.reduce((acc, f) => { acc[f.id] = f; return acc; }, {});

function publicFestival(f) {
  return {
    id: f.id,
    name: f.name,
    group: f.group,
    ethnic: f.ethnic || '',
    date: f.date,
    keyChar: f.keyChar,
    styleName: f.styleName,
    match: f.match,
    theme: f.theme
  };
}

module.exports = { FESTIVALS, FESTIVAL_MAP, publicFestival };
